/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codegenerator;

import Database.Database;
import Database.Fungsi_Query;
import Master.MasterAdmin;
import java.awt.Dimension;
import java.nio.charset.Charset;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Random;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.JMenu;
import javax.swing.JOptionPane;

/**
 *
 * @author AJI-PC
 */
public class LupaPassword extends javax.swing.JInternalFrame {

    Database dbsetting;
    String driver, database, user, pass;
    
    MenuUtama mu = new MenuUtama();
    //Login lg = new Login(new javax.swing.JFrame(),true);
    Fungsi_Query query = new Fungsi_Query();
    Register reg = new Register(new javax.swing.JFrame(),true);
    
    static String tanya, jawab, jawaban, passlama, passbaru,email;
    
    String[] kolom  = new String[6];
    String[] isi    = new String[6];
    
    public String[] Kolom(){
        kolom[0] = "Email";
     
        return kolom;
    }
    
    public String[] Isi(){
        isi[0] = txtPassBaru.getText();
        return isi;
    }
   
    public LupaPassword() {
        initComponents();
        dbsetting = new Database();
        driver    = dbsetting.SettingPanel("DBDriver");
        database  = dbsetting.SettingPanel("DBServer");
        user      = dbsetting.SettingPanel("DBUsername");
        pass      = dbsetting.SettingPanel("DBPassword");
        
        
        email = mu.getDataEmail();
        System.err.println("email "+email);
        validasi(email);
        txtPassBaru.setEnabled(false);
    }
    
    private void validasi(String emailnya){
        //mu = new MenuUtama();
        
        //email = getEmail();
        
        try{
            Class.forName(driver);
            Connection con = DriverManager.getConnection(database, user, pass);
            Statement state = con.createStatement();
            String query = "Select * from MAdmin where Email = '"+emailnya+"'"; 
            ResultSet rs = state.executeQuery(query);
            while(rs.next()){
                passlama = rs.getString(4);
                tanya = rs.getString(5);
                jawab = rs.getString(6);
                System.err.println("tanya"+tanya);
            }
            lblTanya.setText(tanya);
            rs.close();
            state.close();
            con.close();
        }catch(Exception ex){
            System.out.println("tidak ada koneksi "+ex);
	}    
    }
    
    public void login(){
        //mu.setMenu(true);
    } 
    
    public void logout(){
        //mu.setMenu(false);
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtJawab = new javax.swing.JTextField();
        btnOk = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        lblTanya = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPassBaru = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 255, 153));

        jLabel1.setBackground(new java.awt.Color(102, 255, 153));
        jLabel1.setForeground(new java.awt.Color(0, 102, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Lupa Password");
        jLabel1.setOpaque(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setForeground(new java.awt.Color(0, 102, 0));
        jLabel2.setText("Pertanyaan         :");

        jLabel3.setForeground(new java.awt.Color(0, 102, 51));
        jLabel3.setText("Jawaban             :");

        txtJawab.setBackground(new java.awt.Color(51, 51, 51));
        txtJawab.setForeground(new java.awt.Color(204, 204, 204));
        txtJawab.setCaretColor(new java.awt.Color(0, 153, 153));
        txtJawab.setNextFocusableComponent(btnOk);
        txtJawab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJawabActionPerformed(evt);
            }
        });

        btnOk.setText("Ok");
        btnOk.setNextFocusableComponent(txtPassBaru);
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/keluar.png"))); // NOI18N
        btnKeluar.setText("Keluar");
        btnKeluar.setNextFocusableComponent(lblTanya);
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        lblTanya.setForeground(new java.awt.Color(0, 102, 0));
        lblTanya.setText("?");
        lblTanya.setNextFocusableComponent(txtJawab);

        jLabel4.setForeground(new java.awt.Color(0, 102, 0));
        jLabel4.setText("Password Baru :");

        txtPassBaru.setBackground(new java.awt.Color(51, 51, 51));
        txtPassBaru.setForeground(new java.awt.Color(204, 204, 204));
        txtPassBaru.setCaretColor(new java.awt.Color(0, 153, 153));
        txtPassBaru.setEnabled(false);
        txtPassBaru.setNextFocusableComponent(btnSimpan);
        txtPassBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassBaruActionPerformed(evt);
            }
        });

        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ok.png"))); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.setNextFocusableComponent(btnKeluar);
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel4))
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(lblTanya, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txtJawab, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtPassBaru, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTanya)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtJawab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtPassBaru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnKeluar)
                            .addComponent(btnSimpan))
                        .addGap(16, 16, 16))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtJawabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJawabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJawabActionPerformed
   
    
    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
   
        dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        //validasi();
        jawaban= txtJawab.getText();
        
        if(txtJawab.equals("")){
             JOptionPane.showMessageDialog(null,"Jawaban tidak boleh kosong","Error", JOptionPane.INFORMATION_MESSAGE);
        }else if(!jawaban.equals(jawab)){
            JOptionPane.showMessageDialog(null,"Jawaban salah","Error", JOptionPane.INFORMATION_MESSAGE);
        }else{
            txtPassBaru.setEnabled(true);
            JOptionPane.showMessageDialog(null,"Jawaban Benar","Error", JOptionPane.INFORMATION_MESSAGE);
        }      
    }//GEN-LAST:event_btnOkActionPerformed

    private void txtPassBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassBaruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassBaruActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        if(txtJawab.equals("")){
             JOptionPane.showMessageDialog(null,"Jawaban tidak boleh kosong","Error", JOptionPane.INFORMATION_MESSAGE);
        }else if(txtPassBaru.getText().length() < 4){
            JOptionPane.showMessageDialog(null,"Password lemah","Error", JOptionPane.INFORMATION_MESSAGE);
        }else{
            query.Edit(Kolom(), Isi(), "MAdmin", "Email", email);
            JOptionPane.showMessageDialog(null,"data disimpan","Info", JOptionPane.INFORMATION_MESSAGE);
        } 
    }//GEN-LAST:event_btnSimpanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTanya;
    private javax.swing.JTextField txtJawab;
    private javax.swing.JTextField txtPassBaru;
    // End of variables declaration//GEN-END:variables
}
