/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codegenerator;

import Database.ConnectionHelper;
import Database.Database;
import Kode.Maintenance;
import java.awt.Color;
import java.sql.Connection;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author AJI-PC
 */
public class MenuUtama extends javax.swing.JFrame {

    
    
    ConnectionHelper conn;
    Connection connect;
    
    public MenuUtama() {
        initComponents();
        
        cekKoneksi();
        
        this.setLocationRelativeTo(null);
        //this.setSize(800, 600);
        this.setResizable(false);
        setIconnya();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        
        Dimension desktopSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension jInternalFrameSize = this.getSize();
        this.setLocation((desktopSize.width - jInternalFrameSize.width)/2,(desktopSize.height- jInternalFrameSize.height)/2);
        
        pnlMenuUtama.setPreferredSize(desktopSize);
    }
    
    public void setIconnya(){
        java.net.URL url = ClassLoader.getSystemResource("Image/logopit.png");
        Toolkit kit = Toolkit.getDefaultToolkit();
        Image img = kit.createImage(url);
        this.setIconImage(img);
    }

    public JLabel getTxtKoneksi() {
        return txtKoneksi;
    }

    public void setTxtKoneksi(JLabel txtKoneksi) {
        this.txtKoneksi = txtKoneksi;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        dekstop = new javax.swing.JDesktopPane();
        pnlMenuUtama = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtKoneksi = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mHome = new javax.swing.JMenu();
        miLogin = new javax.swing.JMenuItem();
        miLogout = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        miExit = new javax.swing.JMenuItem();
        mMaster = new javax.swing.JMenu();
        miMAdmin = new javax.swing.JMenuItem();
        miMTeknisi = new javax.swing.JMenuItem();
        miMitra = new javax.swing.JMenuItem();
        mKode = new javax.swing.JMenu();
        miMaintenance = new javax.swing.JMenuItem();
        miPorject = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        mPanduan = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PIT Kode Generator");
        setBackground(new java.awt.Color(0, 204, 204));
        setForeground(new java.awt.Color(0, 204, 204));

        dekstop.setBackground(new java.awt.Color(0, 204, 255));

        pnlMenuUtama.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logopit.png"))); // NOI18N

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bannerpit.png"))); // NOI18N

        txtKoneksi.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtKoneksi.setText("Koneksi");
        txtKoneksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtKoneksiMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuUtamaLayout = new javax.swing.GroupLayout(pnlMenuUtama);
        pnlMenuUtama.setLayout(pnlMenuUtamaLayout);
        pnlMenuUtamaLayout.setHorizontalGroup(
            pnlMenuUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuUtamaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(txtKoneksi, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlMenuUtamaLayout.setVerticalGroup(
            pnlMenuUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuUtamaLayout.createSequentialGroup()
                .addGroup(pnlMenuUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMenuUtamaLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(pnlMenuUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)))
                    .addGroup(pnlMenuUtamaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtKoneksi)))
                .addContainerGap(216, Short.MAX_VALUE))
        );

        dekstop.setLayer(pnlMenuUtama, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout dekstopLayout = new javax.swing.GroupLayout(dekstop);
        dekstop.setLayout(dekstopLayout);
        dekstopLayout.setHorizontalGroup(
            dekstopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMenuUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dekstopLayout.setVerticalGroup(
            dekstopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMenuUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(0, 102, 102));

        mHome.setBackground(new java.awt.Color(0, 102, 102));
        mHome.setForeground(new java.awt.Color(255, 255, 255));
        mHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/mnhome.png"))); // NOI18N
        mHome.setText("Home");

        miLogin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        miLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ok.png"))); // NOI18N
        miLogin.setText("Log In");
        miLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLoginActionPerformed(evt);
            }
        });
        mHome.add(miLogin);

        miLogout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        miLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/hapus.png"))); // NOI18N
        miLogout.setText("Log Out");
        mHome.add(miLogout);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/register.png"))); // NOI18N
        jMenuItem1.setText("Register");
        mHome.add(jMenuItem1);
        mHome.add(jSeparator1);

        miExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        miExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/keluar.png"))); // NOI18N
        miExit.setText("Exit");
        miExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miExitActionPerformed(evt);
            }
        });
        mHome.add(miExit);

        jMenuBar1.add(mHome);

        mMaster.setBackground(new java.awt.Color(0, 102, 102));
        mMaster.setForeground(new java.awt.Color(255, 255, 255));
        mMaster.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/mnmaster.png"))); // NOI18N
        mMaster.setText("Master");

        miMAdmin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        miMAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/madmin.png"))); // NOI18N
        miMAdmin.setText("Master Admin");
        mMaster.add(miMAdmin);

        miMTeknisi.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        miMTeknisi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/mteknisi.png"))); // NOI18N
        miMTeknisi.setText("Master Teknisi");
        mMaster.add(miMTeknisi);

        miMitra.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        miMitra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/mmitra.png"))); // NOI18N
        miMitra.setText("Master Mitra");
        mMaster.add(miMitra);

        jMenuBar1.add(mMaster);

        mKode.setBackground(new java.awt.Color(0, 102, 102));
        mKode.setForeground(new java.awt.Color(255, 255, 255));
        mKode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/mnkode.png"))); // NOI18N
        mKode.setText("Kode");

        miMaintenance.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK));
        miMaintenance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/kmaintenance.png"))); // NOI18N
        miMaintenance.setText("Maintenance");
        miMaintenance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miMaintenanceActionPerformed(evt);
            }
        });
        mKode.add(miMaintenance);

        miPorject.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        miPorject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/kproject.png"))); // NOI18N
        miPorject.setText("Project");
        mKode.add(miPorject);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/kemergency.png"))); // NOI18N
        jMenuItem8.setText("Emergency");
        mKode.add(jMenuItem8);

        jMenuBar1.add(mKode);

        mPanduan.setBackground(new java.awt.Color(0, 102, 102));
        mPanduan.setForeground(new java.awt.Color(255, 255, 255));
        mPanduan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/mnpanduan.png"))); // NOI18N
        mPanduan.setText("Panduan");

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/panduan.png"))); // NOI18N
        jMenuItem9.setText("Panduan");
        mPanduan.add(jMenuItem9);

        jMenuItem10.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/about.png"))); // NOI18N
        jMenuItem10.setText("Tentang");
        mPanduan.add(jMenuItem10);

        jMenuBar1.add(mPanduan);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(dekstop)
                .addGap(1, 1, 1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dekstop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    JInternalFrame mMaintenance;
    private void miMaintenanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miMaintenanceActionPerformed
        if(!dekstop.isAncestorOf(mMaintenance)){
            mMaintenance= new Maintenance();
            dekstop.add(mMaintenance);
            try{
                mMaintenance.setSelected(true);
                mMaintenance.setVisible(true);
                mMaintenance.setSize(850, 680);
                Dimension desktopSize = dekstop.getSize();
                Dimension jInternalFrameSize = mMaintenance.getSize();
                mMaintenance.setLocation((desktopSize.width - jInternalFrameSize.width)/2,((desktopSize.height- jInternalFrameSize.height)-20)/2);
            
            }catch (Exception e){
                System.err.println(e.getMessage());
            }
            
        }
    }//GEN-LAST:event_miMaintenanceActionPerformed

    private void miLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLoginActionPerformed
        // TODO add your handling code here:
        Login login = new Login();
        login.setSize(600, 400);
        dekstop.add(login);
        Dimension desktopSize = dekstop.getSize();
        Dimension jInternalFrameSize = login.getSize();
        login.setLocation((desktopSize.width - jInternalFrameSize.width)/2,(desktopSize.height- jInternalFrameSize.height)/2);
        login.show();
    }//GEN-LAST:event_miLoginActionPerformed

    private void txtKoneksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtKoneksiMouseClicked
        cekKoneksi();
    }//GEN-LAST:event_txtKoneksiMouseClicked

    private void miExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_miExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }
    
    Database dbsetting;
    String driver, database, user, pass;
    private void cekKoneksi() {
        dbsetting = new Database();
        driver    = dbsetting.SettingPanel("DBDriver");
        database  = dbsetting.SettingPanel("DBServer");
        user      = dbsetting.SettingPanel("DBUsername");
        pass      = dbsetting.SettingPanel("DBPassword");
        try{
            Class.forName(driver);
            Connection con = DriverManager.getConnection(database, user, pass);
            if(!con.isClosed()){
                txtKoneksi.setText("Online");
                txtKoneksi.setForeground(Color.GREEN);
                con.close();
            }
            
        }catch(SQLException e){
            txtKoneksi.setText("Offline");
            txtKoneksi.setForeground(Color.RED);
            System.err.println("SQL Error"+e.getMessage());
        }catch(ClassNotFoundException e){
            txtKoneksi.setText("Offline");
            txtKoneksi.setForeground(Color.RED);
            System.err.println("Class Error"+e.getMessage());
        }catch(Exception e){
            txtKoneksi.setText("Offline");
            txtKoneksi.setForeground(Color.RED);
            System.err.println("Exception Error"+e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dekstop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu mHome;
    private javax.swing.JMenu mKode;
    private javax.swing.JMenu mMaster;
    private javax.swing.JMenu mPanduan;
    private javax.swing.JMenuItem miExit;
    private javax.swing.JMenuItem miLogin;
    private javax.swing.JMenuItem miLogout;
    private javax.swing.JMenuItem miMAdmin;
    private javax.swing.JMenuItem miMTeknisi;
    private javax.swing.JMenuItem miMaintenance;
    private javax.swing.JMenuItem miMitra;
    private javax.swing.JMenuItem miPorject;
    private javax.swing.JPanel pnlMenuUtama;
    private javax.swing.JLabel txtKoneksi;
    // End of variables declaration//GEN-END:variables

    
}
